### ISSUE TITLE
Make portal usage configurable

### ISSUE THREAD

**Issue by kenticomartinh** [danreeves/react-tether#188]
Hi, we would love to update the react-tether package in our solution to the latest version, and we love it leveraging portals, but we are facing an issue in specific cases.

In our case, we use tether for extra UI (such as popups for editing links) within the rich text editor powered by https://github.com/facebook/draft-js

It works well with the old version (0.6.1) because the tethered content actually lies outside the editor and its contenteditable in the DOM, and therefore does not interfere with the editor by either native or React events. Thanks to the same fact we are able to "nest" contenteditables within the editor even when the editor doesn't natively support it.

However when a portal is in place, it suddenly let's the Portal events through, making the editor react to events it isn't supposed to react to.

We would ideally like to keep everything outside the editor running by default on portal, but fallback to the old version for anything inside the editor. They don't plan to make event bubbling optional within portal feature https://github.com/facebook/react/issues/11387 and simply do not use portals in case where you don't want it, so the suggestion is that whether portal is used or not could be configurable in react-tether. It would be a fairly easy change making the package backwards compatible for complex scenarios.

I can imagine that the same problem may be with other React-based editors leveraging contenteditable and React events.

**Comment by danreeves** [comment]
Hm, that's a valid request but I'm not sure of the best way to solve it. 

I don't really want to allow opting into `unstable_renderSubtreeIntoContainer` because it is in the process of being deprecated and removed. Just not using any sort of portal-ing also doesn't work because the events would still bubble as they do with portals.

As far as I understand it there are 2 options:
 1. Render outside of the component you don't want events bubbling up to
 2. `e.stopPropagation()`

Neither of these belong in this library.

I'm totally open to any suggestions you might have, and feel free to open a PR.

> For tracking purposes:
https://github.com/facebook/react/issues/11387
https://github.com/facebook/react/issues/10143
