### ISSUE TITLE
<StrictMode> Support

### ISSUE THREAD

**Issue by danreeves** [danreeves/react-tether#190]
- `findDOMNode` is deprecated
 - `componentWillUpdate` is deprecated

**Comment by CorinChappy** [comment]
I'm happy to have a go at this, it looks achievable. But I think it might involve changing the API surface, perhaps using render props and passing an "innerRef" as an argument like in [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md). Would you be okay with changing the API in this way?

Additionally, `componentWillUpdate` is also deprecated, but this looks to be a quick win as the contents could be moved to `componentDidUpdate` no problem. Unless I am missing something

**Comment by CorinChappy** [comment]
That was about what I was thinking, but slightly different. An alternative could be to have two separate render props, one for the component and one for the target, something like this (sorry, on a phone so I don't know how this will turn out):
```javascript
<Tether
    renderTarget={(innerRef) => (<div ref={innerRef}/>)}
    renderAttachment={(innerRef) => ...)}
/>
```

It's a slightly more complected upgrade path but if offers a few advantages I think:
Using children means the user would have to either wrap your components in a `<Fragment/>` or an array (meaning you need to key the elements too)
Makes it clearer what element fulfills what function, as the props label what each element will be used for, instead of having to refer to docs to know the order of the elements

This would be a bigger change though, so upgrading would be a bit harder, I not too much so. Let me know what you think!

**Comment by danreeves** [comment]
Ah yeah, that totally makes sense. Two render props sounds like a good option

**Comment by CorinChappy** [comment]
Great :) Any preference on the naming? Tether calls them "element" and "target" so what about `renderTarget` and `renderElement`?

**Comment by danreeves** [comment]
Sounds good to me 👍

**Comment by AsaAyers** [comment]
There is also a problem with `_createContainer`/`updateChildrenComponents` being called from the `constructor`. Strict mode double invokes the constructor, which results in `TetherComponent` creating two `<div>`s in the DOM, but it only uses and cleans up one of them.


> Render phase lifecycles include the following class component methods:
>
> * constructor
> * componentWillMount
> * componentWillReceiveProps
> * componentWillUpdate
> * getDerivedStateFromProps
> * shouldComponentUpdate
> * render
> * setState updater functions (the first argument)
>
> Because the above methods might be called more than once, it’s important that they do not contain side-effects. Ignoring this rule can lead to a variety of problems, including memory leaks and invalid application state. Unfortunately, it can be difficult to detect these problems as they can often be non-deterministic.

https://reactjs.org/docs/strict-mode.html

**Comment by CorinChappy** [comment]
Thanks for the heads up @AsaAyers, hadn't thought of that! Will make sure I can fix that problem too

**Comment by CorinChappy** [comment]
@danreeves would you be happy to drop support for React > 16, due to Portal support? `unstable_renderSubtreeIntoContainer` looks to be on the way out anyway and I want to be able to call the render props in `render`, which `unstable_renderSubtreeIntoContainer` is causing to be a bit of a pain.

This will have to be a major version bump anyway, so seems like a time to do it

Thoughts? Happy to work towards keeping this functionality if you think it's best to keep backwards compatibility

**Comment by danreeves** [comment]
Yeah, let's ditch it. People have had plenty of time to upgrade to 16 by now 👍

**Comment by CorinChappy** [comment]
@danreeves I've pretty much finished now, just cleaning up a bit, it's turned out to be a bit bigger a change than I originally expected!

Just to put some background on why I removed react < 16 support:
I needed to put the render props into the component render function, in order to get potential updates from the functions
This meant that in order to use `unstable_renderSubtreeIntoContainer` we would need to assign during the render function (`this._elementComponent = this.props.renderElement(...)`), something very much not encouraged: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
We could probably put this behaviour back in, as we are probably not going to see this become a problem until Async rendering, which would automatically put them on the `createPortal` version anyway. In which case happy to put back < 16 support with more checks to make sure we aren't doing side effects if createPortal is around

**Comment by CorinChappy** [comment]
Going to put up a PR now so you can review the code, ut I have only quickly updated the README. Will try and give more details in the README over the next couple of days. Any suggestions for documentation updates are welcome!

**Comment by AsaAyers** [comment]
This change is specifically being made to fix a warning in React 16 that will turn into a bug in React 17. This seems like an ideal time to drop support for React < 16 to me.
