### ISSUE TITLE
renderElementTo yet not working

### ISSUE THREAD

**Issue by aseem2625** [danreeves/react-tether#54]
As per [comment](https://github.com/souporserious/react-tether/issues/16#issuecomment-210081553) issue is fixed but it not working for me!

[Same issue](https://github.com/souporserious/react-tether/issues/44) but no resolution

**Comment by Eugene-Sviridov** [comment]
@aseem2625 Hi. I've checked source code and found that it works if you add this two props at the same time
```
renderElementTo=".toolbox-wrapper"
bodyElement={document.querySelector('.toolbox-wrapper')}
```

**Comment by danreeves** [comment]
Yep, this is correct. `react-tether` is working correctly, `tether` itself has the issue.

Tether requires the `renderElementTo` element to be `position: static;`, otherwise it will default to `document.body`. I've added this explanation to the [readme](https://github.com/danreeves/react-tether#renderelementto-proptypesstring) and an [example page](https://danreeves.github.io/react-tether/renderelementto/) to demonstrate. (Code for the demo [here](https://github.com/danreeves/react-tether/tree/master/tests/examples/renderelementto)).

`bodyElement` _is_ a workaround but it can behave unexpectedly.
